### ISSUE TITLE
Presentaciones

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Curso-In-Company-Liquid-Squad#1]
Hola!

Usemos este espacio para conocernos un poco más... :-)

Recordad que estos [_issues_](https://github.com/Fictizia/Curso-In-Company-Liquid-Squad/issues) nos permiten abrir y participar en debates, compartir recursos, plantear preguntas y muchas cosas más! 

Podemos usar [Markdown](https://guides.github.com/features/mastering-markdown/) para salirnos del texto plano y enriquecer nuestras aportaciones.

**Comment by aoperez** [comment]
Hola soy Alberto Ocaña.

Empecé currando con backend con PHP, Python (con frameworks como Symfony y Django) y actualmente FrontEnd con Angular, Node.js, etc.

**Comment by nastes** [comment]
Buenas, soy Daniel Arenas

Maquetador desde hace 15 años con aspiraciones a algo más.

Por cierto, ¿hay que abrirse cuenta en cloud9? (por lo de darles los datos de la tarjeta de crédito...)

**Comment by UlisesGascon** [comment]
@nastes en principio aún no necesitamos crearnos una cuenta de c9. Os mandaré una invitación cuando veamos Nodejs que os evitará tener que meter la tarjeta de credito ;-)

**Comment by dcastillom** [comment]
Hola, soy Daniel Castillo
Estudié derecho, pero hace algunos años decidí cambiar mi carrera profesional para dedicarme a estas cosas de los *frotenderismos*. Formé parte de la primera edición de Ironhack. Quiero aprender y divertirme con javascript.

**Comment by javiperezdepedro** [comment]
Hola soy Javi Pérez

Vengo del mundo de la publi. Anteriormente he estado trabajando en los departamentos de producción digital de Shackleton o Grey. Estoy seguro de que voy a aprender un montón en este curso y espero aprovecharlo al máximo.
